# Site settings
title: Anders Östlin
email: anders.ostlin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal home page for Anders Östlin.
  Expect to find some information about my personal projects here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andersöstlin.se" # the base hostname & protocol for your site
twitter_username: barksten
github_username:  barksten

# Build settings
markdown: kramdown
highlighter: pygments
github: [Repository metadata]
safe: true
lsi: false

